### ISSUE TITLE
Depth or disparity map

### ISSUE THREAD

**Issue by chapa17** [atapour/monocularDepth-Inference#11]
Hello,

Thank you very much for sharing your work. I am trying to obtain depth map from my own dataset with your code. Further I need to construct 3D point cloud using the depth information. I need depth values to convert them into x, y and z points. As per [this](https://github.com/atapour/monocularDepth-Inference/issues/8#issuecomment-616419292), the resultant image is the disparity map hence I consider the tensor variable `fake_C` (in this case) from which it is generated also has disparity values. So I can directly invert the tensor variable and obtain the depth values or the tensor variable already has absolute depth values?

Thank you!

**Comment by atapour** [comment]
The results are disparity and need to be inverted to get depth values.

**Comment by chapa17** [comment]
Thank you for your quick response. I did not find any variable providing depth values so far. Does any variable exist or it has to be computed?

**Comment by atapour** [comment]
Depth would need to be computed from the result.
