### ISSUE TITLE
Endoscope images

### ISSUE THREAD

**Issue by YJonmo** [atapour/monocularDepth-Inference#5]
Hi, 

Thanks for the code. 
I am about to use this repo for training to be able to estimate the depth for the images acquired from a stereo endoscope under the water. As I can see this and most of the mono depth methods are applied for the street and cars. Is there anything that I should do or not to do for training the model when my aim is to get the depth for underwater and small distant objects?  

Also I noticed the amount of overlap between stereo images for me is not as much as typical images from the street views. So my problem is a smaller amount of the overlap. 

Thanks for reading

**Comment by atapour** [comment]
Hello,

This repo is based on a directly supervised approach using pixel-perfect ground truth synthetic depth images. It is therefore not suited for stereo data.

There are other interesting works that do use stereo image pair in their training, such as:
https://github.com/mrharicot/monodepth

As for your question about the differences between outdoor driving scenarios and other applications such as the one you are interested in, there shouldn't be much as long as enough robust data is available. Of course, in case of stereo imagery, there should enough features in the scene to make disparity estimation possible, which might be a problem in underwater images. However, the approach of the repo linked above is very strong and should be able to deal with this.
