### ISSUE TITLE
Question about DATASET

### ISSUE THREAD

**Issue by fthydd** [atapour/monocularDepth-Inference#6]
Hi Atapour

Thanks for sharing. The idea is really great!!
I wonder if you can share the dataset with me.

**Comment by atapour** [comment]
The actual data set of imges is quite large. All data was captured using code inspired by: https://github.com/aitorzip/DeepGTAV

**Comment by lysektomas** [comment]
Hi, how did you get depth map from DeepGTAV? If i see correctly, they are only returing RGB images.
Thanks!
