### ISSUE TITLE
Training scheme of monocularDepthCGAN and CycleGAN

### ISSUE THREAD

**Issue by HuynhLam** [atapour/monocularDepth-Inference#7]
Hi,

The paper states 

> Our approach consists of two stages, the operations of which are carried out by two separate models, trained at the same time.

Is it possible for you to explain more about the training scheme of two models in stage 1 (the monocular depth estimation model) and stages 2 (the domain adaptation model)?

There is not the joint loss for both stages so I suppose two models are training at the same time but their weights are updated separately, aren't they?

I am not so sure about this, so I (and maybe others) would be very appreciated if you can talk a little more details about this.

Thanks in advance.

**Comment by atapour** [comment]
Yes. The two models are completely independent and could be trained completely separately.

This was done to disentangle the two tasks of style transfer and depth estimation so the hypothesis that style transfer done separately can perform domain adaptation cam be tested.
