### ISSUE TITLE
How to get real depth in meters?

### ISSUE THREAD

**Issue by LiZhenLiangLee** [atapour/monocularDepth-Inference#8]
Hi. I want to get the absolute depth values in meters. But the run_test.py just output depth image. Can your model output the real depth value?

**Comment by tlhcelik** [comment]
> Hi. I want to get the absolute depth values in meters. But the run_test.py just output depth image. Can your model output the real depth value?

Do you know how can i use video file or camera ?

**Comment by atapour** [comment]
The model outputs disparity maps, and the absolute depth. You could convert disparity to depth via Z = fB/d.
