### ISSUE TITLE
How can i use video file or camera ?

### ISSUE THREAD

**Issue by tlhcelik** [atapour/monocularDepth-Inference#9]
Hi, i run this program with ./Examples images. But i should run with some video file.
How can i run video file or camera ?

**Comment by atapour** [comment]
Hi. There is no support in the code for video files. You could potentially use OpenCV (VideoCapture) to read the frames one by one and pass them into the model. There is a tutorial here for how to get started with videos using opencv: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html

**Comment by tlhcelik** [comment]
> Hi. There is no support in the code for video files. You could potentially use OpenCV (VideoCapture) to read the frames one by one and pass them into the model. There is a tutorial here for how to get started with videos using opencv: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html

Thank for speedy reply. 
I know how can i use cv2.VideoCapture() but i don't understand your code. Which line get frame put (model.set_input(frame)) and show depth image ?

I try this, is not working. Throwing error.

`import os

from arguments import Arguments
from data import CreateDataLoader
from models import create_model
from util import save_images
import cv2

if __name__ == '__main__':
	args = Arguments().parse()

	data_loader = CreateDataLoader(args)
	dataset = data_loader.load_data()
	model = create_model(args)

        cam = cv2.VideoCapture(0)
	while True:
                _, frame = cam.read()
		model.set_input(frame)
		model.test()
		visuals = model.get_current_visuals()
		cv2.imshow("im",visuals["depth"])
		if (cv2.waitKey(1) & 0xFF == ord('q')):
			break
			
cv2.destroyAllWindows()`

**Comment by atapour** [comment]
The code uses a custom dataset class (TestDataset) here: https://github.com/atapour/monocularDepth-Inference/blob/master/data/single_dataset.py

The image are read one by one from the input directory (./Examples in the example code) using PIL. This portion of the code needs to completely change to enable reading from video file directly.

Alternatively, you can process the video beforehand and generate individual frames which you can then pass into the model without changing the code.

**Comment by tlhcelik** [comment]
Okey thank you for help. I'll try change code.
